### ISSUE TITLE
git ignore for JS files

### ISSUE THREAD

**Issue by rahulagarwal13** [hasura/ddn_beta_ecommerce#27]
special gitignore, if we change them they should be tracked. But the project language should not change to javascript. Is this possible?
https://github.com/hasura/ddn_beta_ecommerce/tree/main/Composability/ProductHomePage/REST%20Implementation

**Comment by soorajshankar** [comment]
This seems tricky, we can either make these files markdown (.md) files so that we get both code highlights and easier way to visualise the comments

**Comment by soorajshankar** [comment]
https://github.com/hasura/ddn_beta_ecommerce/pull/39
^ this could potentially solve this
