### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by rahulagarwal13** [hasura/ddn_beta_ecommerce#32]
- Including Schema Information and diagram
- Add things like -  it will take time to build and why it is taking time to build
- Any other thing to make it look professional
- Add license to it?

**Comment by soorajshankar** [comment]
Discussions with Manas 

1. Talk about all subgraphs, high level models and different data sources.
2. expand the Models with Commands (it should tell that it is powered by TS connector)
3. Screenshot from rootview (console)
4. use DB icons , show multi DB on subgraphs 
5. Intro: talk about different subgraphs backed by one or more data connectors
6. Connector builds : explain what happens under the hood. (why so much time?- infra)

**Comment by soorajshankar** [comment]
Licence PR [here ](https://github.com/hasura/ddn_beta_ecommerce/pull/42)
