### ISSUE TITLE
Verify and clean REST API Implementation

### ISSUE THREAD

**Issue by rahulagarwal13** [hasura/ddn_beta_ecommerce#37]
https://github.com/hasura/ddn_beta_ecommerce/tree/main/Composability/ProductHomePage/REST%20Implementation

Check all of these files. Verify that code looks okay. Does not need to be operational but should look realistic.
Cleaning means - add more comments or remove comments wherever required

**Comment by soorajshankar** [comment]
Looks good to me. 

* We have shown some imports here which is not defined/shown anywhere else - but given the scope of the demo I think its okay to not show them
* I think in part6, after the performance section, we can mention shortly about JS being single threaded while DDN parallelise threads it in real sense with rust using the maximum compute power.

**Comment by rahulagarwal13** [comment]
Thanks for the feedback.

- Let's make change as per second point

- for third point - let's come up with a query using nested filtering for different databases. See if a query makes sense with all of Postgres, Mongo or Clickhouse. Or we can do two queries with combination of two Dbs. And then provide REST implementation for that one or two queries. IN the future we would need something similar for aggregations and nested aggregations. For Mongo - create a ProductDetailPageQuery and Clickhouse - see if you can augment the ProductHomePage Query with a recentlyviewed section or it could be a UserProfileQuery or maybe part of ProductDetailPageQuery. Make a separate folder for such queries along with the REST implementation
(third point is not urgent for this week)
